#Function that generates a new X
#New X is generated by performing 1 or 3 options
# A. Create New Individual
# B. Delete an Individual
# C. Move photos


new.X.create-function(X,t,lambda){
  
  #Number of indidivduals in current X
  current.n.ind<-max(X[,3]) 
  
  #Used to account for when indidivuals are unintentionally removed
  continue<-"TRUE"
  
  while(continue=='TRUE'){
      new.X<-X
      
      #Select number of occasions individual is seen on and which occasions
      n.occasion<-sample(1:t,size=1)
      occasions<-sort(sample(1:t,size=n.occasion))
      
      #Next we select the ID for the individual
      new.individual<-sample(seq(from=.5,to=(current.n.ind+.5),by=1),1)
      
      #Renumber the individuals
      new.X[which(new.X[,3]>new.individual),3]=new.X[which(new.X[,3]>new.individual),3]+1
      
      #For each of the occasions the indidivual is seen on we pull photos from other individuals
      #For each occasion we pull lambda plus or minus 1
      
      for(i in 1:n.occasion){
        #Select number of photos to remove
        
        n.photos<-ceiling(lambda)
        ##Select the location of photos to be removed
        remove.location<-sample(X[which(X[,2]==occasions[i]),1],n.photos)
        #Sets the location of the photos to the new indidivual
        new.X[remove.location,3]<-new.individual+.5
      }
      
      #Need to account for when all of the photos are removed for an individual
      if(length(unique(new.X[,3])) == (current.n.ind+1)) {continue="FALSE"}
    }
    return(list("new.X"=new.X,'photos'=remove.location,'new.ID'=(new.individual+.5)))
    
}