#Function that generates a new X
#New X is generated by performing 1 or 3 options
# A. Create New Individual
# B. Delete an Individual
# C. Move photos



new.X.fun<-function(q1,q2,X,t,lambda,k){
  #Number of indidivduals in current X
  current.n.ind<-max(X[,3]) 
  
  # First we choose which action to take
  action<-runif(1)
  
  #Used to account for when indidivuals are unintentionally removed
  continue<-"TRUE"
  
  if(action <=q1){  #We are adding an individual
    while(continue=='TRUE'){
    new.X<-X
    
    #Select number of occasions individual is seen on and which occasions
    n.occasion<-sample(1:t,size=1)
    occasions<-sort(sample(1:t,size=n.occasion))
    
    #Next we select the ID for the individual
    new.individual<-sample(seq(from=.5,to=(current.n.ind+.5),by=1),1)
    
    #Renumber the individuals
    new.X[which(new.X[,3]>new.individual),3]=new.X[which(new.X[,3]>new.individual),3]+1

    #For each of the occasions the indidivual is seen on we pull photos from other individuals
    #For each occasion we pull lambda plus or minus 1
    
    for(i in 1:n.occasion){
      #Select number of photos to remove
      
      n.photos<-ceiling(lambda)
      ##Select the location of photos to be removed
      remove.location<-sample(X[which(X[,2]==occasions[i]),1],n.photos)
      #Sets the location of the photos to the new indidivual
      new.X[remove.location,3]<-new.individual+.5
    }
    
    #Need to account for when all of the photos are removed for an individual
    if(length(unique(new.X[,3])) == (current.n.ind+1)) {continue="FALSE"}
    }
    return(list("new.X"=new.X,'decision'='new','photos'=remove.location,'new.ID'=(new.individual+.5)))
    
  }else if (action>q1 & action <=q2){  #We are deleting an indidivual
    
    new.X<-X
    #Select individual to delete
    lost.ID<-sample(1:current.n.ind,size=1)
    photos.allocate<-X[which(X[,3]==lost.ID),1]
    
    new.X[photos.allocate,3]<-NA
    
    new.ID<-sort(unique(new.X[,3]))  #Current IDs in new X
    
    #Since an ID was lost we renumber the individuals    
    temp<-c(1,lost.ID,(max(new.ID)+1))
    for(j in 1:2){
        new.X[which(new.X[,3]>=temp[j]&new.X[,3]<temp[j+1]),3]<-new.X[which(new.X[,3]>=temp[j]&new.X[,3]<temp[j+1]),3]-(j-1)
    }
    
    new.ind<-max(new.X[,3],na.rm=TRUE) #Computes the number of individuals in new X
    
    #Reallocate photos
    for(i in 1:length(photos.allocate)){
      new.X[photos.allocate[i],3]<-sample(1:new.ind,size=1)
    }
    
    return(list("new.X"=new.X))
    
  }else{ #Reallocate photo
    while(continue=='TRUE'){
    new.X<-X
    #Select a capture occasion
    cap.occasion<-sample(1:t,1)
    
    #Photos in selected capture occasion
    remove.location<-sample(X[which(X[,2]==cap.occasion),1],k)
    new.X[remove.location,3]<-NA
    
    #Reallocate the photos
    for(i in 1:length(remove.location)){
      new.X[remove.location[i],3]<-sample(1:current.n.ind,size=1)
    }
    
    if(length(unique(new.X[,3])) == (current.n.ind)) {continue="FALSE"}
    }
    return(list("new.X"=new.X))
  }
  
}